### ISSUE TITLE
testのなかのfooディレクトリ

### ISSUE THREAD

**Issue by S-Shimotori** [nabedge/mixer2#20]
このfooディレクトリは何のテストをするものなのでしょう？どこかのテストで使うためのものですか？
[mixer2/src/test/java/org/mixer2/spring/webmvc/foo at master · S-Shimotori/mixer2](https://github.com/S-Shimotori/mixer2/tree/master/src/test/java/org/mixer2/spring/webmvc/foo)

**Comment by nabedge** [comment]
ViewResolverChainTest needs foo/BarView class. Thank you !
