### ISSUE TITLE
DevelopementEnvironmentのページでの、STSのインストール方法の説明が古くなっている

### ISSUE THREAD

**Issue by NakanoMizuki** [nabedge/mixer2#21]
環境構築のページ(http://mixer2.org/site/ja/DevelopmentEnvironment.html)
でのSpring Tool Suite(STS)のインストール方法に関して、ドキュメントが古いと思われます。

現在の説明内容
> 公式サイトからインストーラをダウンロードし、インストーラを用いたインストール方法が説明されている。

実際
> 公式サイトからダウンロードできる物がtar.gz形式でした。
> これを解凍して実行するとSTSを使用できました。(Mavenも含まれていました。)
> OS X Yosemite 10.10.3で確認しました。

改善案
> 公式サイトよりtar.gzをダウンロードし、解凍する。
> 解凍後のsts-bundlle/sts-3.6.4.RELEASE/STS.app を実行する。 (3.6.4は2015-06-27時点の最新バージョン)

**Comment by nabedge** [comment]
Thanks !  https://github.com/nabedge/mixer2/commit/4b799f6dbeb3c01be8b29939caca82d0d6f2250d
